### ISSUE TITLE
There are lots of blanks at the end of the code

### ISSUE THREAD

**Issue by iesv** [amirchev/OBS-Lyrics#10]
![image](https://user-images.githubusercontent.com/16969250/108585286-92c10c80-7382-11eb-807c-61c1b0d8d9da.png)

**Comment by amirchev** [comment]
Has this issue been resolved @iesvme ?

**Comment by iesvme** [comment]
No. This is what vim shows. Maybe when coding and typing extra spaces.

**Comment by amirchev** [comment]
Thanks for the info. Can you show me where you got this statistic? We just started using a code beautifier, so perhaps it should get rid of the extra white space.

**Comment by iesv** [comment]
Not resolved. The developers seem to have abandoned the project.
