### ISSUE TITLE
The title source doesn't hide with the text source finished.

### ISSUE THREAD

**Issue by iesvme** [amirchev/OBS-Lyrics#12]
The title source doesn't hide with the text source finished.

**Comment by amirchev** [comment]
@DCStrato

**Comment by wzaggle** [comment]
Title source currently does not hide by design.  I will look to make this an option to hide ALL text if there are no lyrics to display.

**Comment by amirchev** [comment]
Thanks @wzaggle, this feature request is included in [1.4.2 and later](https://github.com/amirchev/OBS-Lyrics/releases/tag/v1.4.3).
