### ISSUE TITLE
Experiencing error

### ISSUE THREAD

**Issue by Smallbutloud** [amirchev/OBS-Lyrics#16]
lyrics.lua producing this error when I tried to add the script:

[lyrics.lua] Error calling script_load: ...urces/data/obs-plugins/frontend-tools/scripts/lyrics.lua:608: attempt to call field 'os_opendir' (a nil value)
[lyrics.lua] Failed to call script_properties for obs_lua_script_get_properties: ...urces/data/obs-plugins/frontend-tools/scripts/lyrics.lua:765: attempt to call field 'obs_source_get_unversioned_id' (a nil value)

**Comment by amirchev** [comment]
Hi, make sure you are using newest version of script AND newest version of OBS. Please report back with versions of both. Thanks!

**Comment by Smallbutloud** [comment]
Thank you, I will try again.

**Comment by Smallbutloud** [comment]
that worked for me!

Thanks

>

**Comment by amirchev** [comment]
Good to hear!
