### ISSUE TITLE
Mac instructions are unclear

### ISSUE THREAD

**Issue by ntatko** [amirchev/OBS-Lyrics#17]
I am on a mac, attempting to show lyrics in front of a video feed. Admittedly, I am new to OBS, but nonetheless.

Here's my setup:
<img width="299" alt="Screen Shot 2021-03-15 at 2 58 20 AM" src="https://user-images.githubusercontent.com/37306038/111121202-5a07f380-853a-11eb-9157-02991671bb03.png">

I'm looking for the text source back in the script, and it doesn't show up.
<img width="327" alt="Screen Shot 2021-03-15 at 2 57 56 AM" src="https://user-images.githubusercontent.com/37306038/111121209-5d02e400-853a-11eb-882c-4bfd9d4e9f09.png">
Am I missing something, or is this a bug?

Thanks for any help you may have.

**Comment by amirchev** [comment]
@ntatko Hi, I'm not sure why it's not showing. In the "Scripts" window, click the refresh button and then see if the source populates. Also, try not using a FreeType 2 text source, but a GDI text source. See if that helps.

**Comment by ntatko** [comment]
>  try not using a FreeType 2 text source, but a GDI text source

GDI is a windows only option - I have no such option on my mac.

**Comment by amirchev** [comment]
Hey, I don't have a mac unfortunately. No other mac users have reported this issue. Please try updating both the script and OBS, then make sure to follow the instructions on the [main page ](https://github.com/amirchev/OBS-Lyrics)of this repository.

**Comment by amirchev** [comment]
Has this issue been resolved? @ntatko

**Comment by ntatko** [comment]
No, it's still an issue, but I ended up not using this plugin for my event. You can close the issue if you want.
