### ISSUE TITLE
Obs-Lyrics 1.4.2: It shows that lyrics.lua:954: attempt to concatenate local 'suffix' (a nil value) when deleting song.

### ISSUE THREAD

**Issue by iesvme** [amirchev/OBS-Lyrics#20]
Obs-Lyrics 1.4.2: It shows that lyrics.lua:954: attempt to concatenate local 'suffix' (a nil value) when deleting song.

**Comment by amirchev** [comment]
I think this has been resolved in 1.4.2 and [later](https://github.com/amirchev/OBS-Lyrics/releases/tag/v1.4.3).
