### ISSUE TITLE
Pepared Lyrics Crash when changing the selected lyrics

### ISSUE THREAD

**Issue by jbeye** [amirchev/OBS-Lyrics#23]
Hi,

not everytime, but very often the prepared Lyrics freezes/crashes my OBS-Studio when I want to change the lyrics to the another song.
I'm using the script for the devine service in our congragaton in Nothern Germny to show the lyrics in the stream.
Everytime OBS Freezes/Crashes the stream stops untlil I restart OBS.
So this is quite anoying.
We are running an Windows based system.
For the moment I added multiple Prepared lyrics and disable them, so wehen want to change to the new song disable the old one and enble the one. This works for the moment.
I wasn't able to find any logs of the crash.

The songs folder contains about 450 Songs.
I already had to replace the German special characters (ä,ö,ü and ß) in the filenames, to make it running.

What I still do have left are characters like: , and ' 

Could you please help me?

**Comment by wzaggle** [comment]
[lyrics.zip](https://github.com/amirchev/OBS-Lyrics/files/7114272/lyrics.zip)
Jbeye 
Attached is a version you can try to see if it still locks up.  I am unable to duplicate your problem, so I am only guessing at things that might be causing it on your hardware.  

D.C.

**Comment by jbeye** [comment]
Hi,

thank you for your quick response.
I've now tested about an hour with your Version, but no changes.
It still keeps freezing my OBS Studio.

For now I rethinked my approach and will use the ability with the prepared songs.
For now it's flexibel enough for me.

But with every new version I will keep testing.
I know that Windows is not the common OS for such thing, but that's the hardware we got.

When I have time I will try to improve my python skills, but for now I'm more familiar with JVM languages.

I really so like your script, so keeep going.

Kind regards, Jan

**Comment by iesv** [comment]
I have the same problem!

**Comment by iesv** [comment]
> 

hello, Jbeye. Would you tell me what is your best way to resolve this crash/freezing?

**Comment by jbeye** [comment]
@iesv Unfortnely I stopped using this script, I'm now using Luma Keying and an extra Software wich has an Web Service which I display in an Browser Source.

**Comment by iesv** [comment]
Oh, Thank you for your reply!
