### ISSUE TITLE
It cannot show Chinese. It doesn't seem to support UTF-8

### ISSUE THREAD

**Issue by iesvme** [amirchev/OBS-Lyrics#9]
![image](https://user-images.githubusercontent.com/16969250/108580992-0ce49780-7369-11eb-9272-c621bec369fd.png)

**Comment by amirchev** [comment]
Thank you for your post. Where is it not showing? I see Chinese characters there...

**Comment by iesvme** [comment]
No, it is a messy code instead of correct letter.
in the other hand, It will flash on screen when launching the OBS.
And, would you add such as the "delete prepared songs" button on panel in future? so that It can delete a certain song.

btw, Thank you for developing this such a good plug! I'm using it in Christian Church, too. May God bless you!

**Comment by iesvme** [comment]
![image](https://user-images.githubusercontent.com/16969250/108623632-ec0c6700-747a-11eb-8a19-71aaef83c278.png)

**Comment by amirchev** [comment]
Okay, I see that the prepared name is different than the displayed name in the directory. I noticed there is a problem with Russian characters too. I have to look into it closer, but I'm not sure that is a script problem, or more of an OBS problem. We'll see.

**Comment by amirchev** [comment]
If you see [here](http://www.lua.org/versions.html), UTF-8 is only supported after Luajit 5.3, but OBS uses 5.2 I think. I'll see if there is a way I can include an outside UTF-8 library...

**Comment by iesvme** [comment]
Thank you amirchev so much!
I find this one. could it be helpful for you? 
https://github.com/starwing/luautf8

**Comment by iesvme** [comment]
Can lua call DOS command to create a file name?

**Comment by amirchev** [comment]
> 
> 
> Can lua call DOS command to create a file name?

I believe so

**Comment by amirchev** [comment]
Resolved by @DCStrato in #19
